### ISSUE TITLE
Invalid -Wlogical-op option for clang 

### ISSUE THREAD

**Issue by egirault** [airbus-seclab/c-compiler-security#17]
Hello,
Thanks for this repo, it's great!
I think there is a small error in the clang TL;DR section of the README; it seems that the `-Wlogical-op` option is GCC only and is not supported by clang. It is not listed in the [reference](https://releases.llvm.org/12.0.0/tools/clang/docs/DiagnosticsReference.html).
This is what I get with `clang-12 -Wlogical-op  foo.c -o foo`:
```
warning: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Wunknown-warning-option]
```

**Comment by trou** [comment]
Indeed, thanks for spotting it!
